package com.shape;
class RunnableThread implements Runnable
{
    public void run()
    {
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
        System.out.println("I am a Thread");
    }
}
class RunnableThread2 implements Runnable
{
    public void run()
    {
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
        System.out.println("I am a Thread 2");
    }
}
public class a103Runnable_Method {
    public static void main(String[] args) {
        RunnableThread t1 = new RunnableThread();
        Thread g1 = new Thread(t1);
        RunnableThread2 t2 = new RunnableThread2();
        Thread g2 = new Thread(t2);
        g1.start();
        g2.start();
    }
}
